"use strict";
const { execSync } = require("child_process");
console.log("🔨 Building...");
execSync("npm run build", { stdio: "inherit" });
console.log("🚀 Adding dist/ to git");
execSync("git add dist", { stdio: "inherit" });
const msg = `Deploy build ${new Date().toISOString().slice(0,10)}`;
execSync(`git commit -m "${msg}"`, { stdio: "inherit" });
console.log("📤 Pushing to GitHub");
execSync("git push origin main", { stdio: "inherit" });
console.log("✅ Deploy finished");