"use strict";
Object.defineProperty(exports, "__esModule", { value: true });
exports.default = {
  name: "Deploy to GitHub Pages",
  on: {
    push: {
      branches: ["main"] // altere se sua branch de produção for diferente
    }
  },
  jobs: {
    build_and_deploy: {
      runs-on: "ubuntu-latest",
      steps: [
        {
          name: "Checkout repository"
        },
        {
          name: "Setup Node"
          uses: "actions/setup-node@v4"
          with: {
            node-version: "20"
          }
        },
        {
          name: "Install dependencies"
          run: "npm ci"
        },
        {
          name: "Build"
          run: "npm run build"
        },
        {
          name: "Deploy to GitHub Pages"
          uses: "peaceiris/actions-gh-pages@v4"
          with: {
            github_token: "GITHUB_TOKEN"
            publish_dir: "dist"
            publish_branch: "gh-pages"
            force_orphan: true
          }
        }
      ]
    }
  }
};